export const SERVER_URL = "https://paste.yurzhang.com";
export const API_URL = "https://paste.yurzhang.com/api";

export const supportedLangs = {
  html: "html",
  xml: "xml",
  css: "css",
  js: "javascript",
  adoc: "plaintext",
  sh: "shell",
  c: "c",
  cs: "csharp",
  cpp: "cpp",
  cmake: "plaintext",
  elixir: "elixir",
  go: "go",
  hs: "plaintext",
  java: "java",
  json: "json",
  json5: "json",
  kt: "kotlin",
  tex: "plaintext",
  lua: "lua",
  makefile: "plaintext",
  md: "markdown",
  pascal: "pascal",
  perl: "perl",
  php: "php",
  py: "python",
  rb: "ruby",
  rust: "rust",
  scala: "scala",
  toml: "plaintext",
  ts: "typescript",
  yml: "yaml",
};

export const langDisplay = {
  html: "HTML",
  xml: "XML",
  css: "CSS",
  js: "JavaScript",
  adoc: "AsciiDoc",
  sh: "Bash",
  c: "C",
  cs: "C#",
  cpp: "C++",
  cmake: "CMake",
  elixir: "Elixir",
  go: "Go",
  hs: "Haskell",
  java: "Java",
  json: "JSON",
  json5: "JSON5",
  kt: "Kotlin",
  tex: "LaTeX",
  lua: "Lua",
  makefile: "Makefile",
  md: "Markdown",
  pascal: "Pascal",
  perl: "Perl",
  php: "PHP",
  py: "Python",
  rb: "Ruby",
  rust: "Rust",
  scala: "Scala",
  toml: "TOML",
  ts: "TypeScript",
  yml: "YAML",
};
