export const supportedLanguages = {
  text: "Plain Text",
  asciidoc: "AsciiDoc",
  asm: "Assembly",
  astro: "Astro",
  bat: "Batch File",
  bibtex: "BibTeX",
  c: "C",
  cmake: "CMake",
  "common-lisp": "Common Lisp",
  coq: "Coq",
  cpp: "C++",
  csharp: "C#",
  css: "CSS",
  csv: "CSV",
  dart: "Dart",
  diff: "Diff",
  docker: "Dockerfile",
  elixir: "Elixir",
  go: "Go",
  haskell: "Haskell",
  html: "HTML",
  java: "Java",
  javascript: "JavaScript",
  json: "JSON",
  jsx: "JSX",
  kotlin: "Kotlin",
  latex: "LaTeX",
  lean: "Lean 4",
  lua: "Lua",
  make: "Makefile",
  markdown: "Markdown",
  matlab: "MATLAB",
  nix: "Nix",
  ocaml: "OCaml",
  pascal: "Pascal",
  perl: "Perl",
  php: "PHP",
  powershell: "PowerShell",
  python: "Python",
  ruby: "Ruby",
  rust: "Rust",
  scala: "Scala",
  scheme: "Scheme",
  shellscript: "Shell",
  shellsession: "Shell Session",
  sql: "SQL",
  svelte: "Svelte",
  tex: "TeX",
  toml: "TOML",
  tsx: "TSX",
  typescript: "TypeScript",
  typst: "Typst",
  verilog: "Verilog",
  vue: "Vue",
  wasm: "WebAssembly",
  wolfram: "Wolfram",
  xml: "XML",
  yaml: "YAML",
  zig: "Zig",
};

export const ID_CHARSET =
  "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
